route:
  group_by: [Alertname]
  # Send all notifications to me.
  receiver: gmail

receivers:
- name: gmail
  email_configs:
  - to: anthonywindebank@gmail.com
    from: anthonywindebank@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: "anthonywindebank@gmail.com"
    auth_identity: "anthonywindebank@gmail.com"
    auth_password: <secret>
