groups:
- name: node.rules
  rules:
  - alert: ServerReboot
    expr: system_time < 600
    labels:
      severity: critical
    annotations:
      summary: Server has rebooted recently!
  - alert: PrometheusTargetMissing
    expr: up == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Prometheus target missing (instance {{ $labels.instance }})"
      description: "A Prometheus target has disappeared. An exporter might have crashed or a host is down.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
