groups:
- name: Server
  rules:
  - alert: ServerReboot
    expr: (node_time_seconds - node_boot_time_seconds) < (19*60) >= (5*60)
    labels:
      severity: page
    annotations:
      summary: Server has rebooted recently!
